# Generated by Django 3.2.5 on 2021-07-18 11:47

import competitions.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_auto_20210718_1147"),
        ("organisations", "0004_auto_20210718_1147"),
        ("competitions", "0004_competition_competition_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="school_text",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="school (text)"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="competition_date",
            field=models.DateField(null=True, verbose_name="competition date"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(
                help_text="For example: Van Melsenprijs 2021",
                max_length=20,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                related_query_name="competitions",
                to="organisations.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="registration_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="registration end"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="registration_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="registration start"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="slug",
            field=models.SlugField(max_length=20, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="student",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="address 1"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="address 2"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=20, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=20, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                related_query_name="authors",
                to="competitions.submission",
                verbose_name="submission",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="town",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="town"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="zip",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter zip code in this format: '1234 AB'",
                        regex="^[1-9][0-9]{3} (?!SA|SD|SS)[A-Z]{2}",
                    )
                ],
                verbose_name="zip",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="abstract",
            field=models.TextField(verbose_name="abstract"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                related_query_name="submissions",
                to="competitions.competition",
                verbose_name="competition",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                related_query_name="submissions",
                to="organisations.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="document",
            field=models.FileField(
                upload_to=competitions.models.submission_upload_path,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="jury_report",
            field=models.TextField(blank=True, null=True, verbose_name="jury report"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="nominated",
            field=models.BooleanField(default=False, verbose_name="nominated"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="nomination_report",
            field=models.TextField(blank=True, verbose_name="nomination report"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="nomination_score",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nomination score"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="prize",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="prize"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                related_query_name="submissions",
                to="schools.school",
                verbose_name="school",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="slug",
            field=models.SlugField(max_length=120, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="title",
            field=models.CharField(max_length=100, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="address 1"
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="address 2"
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supervisors",
                related_query_name="supervisors",
                to="organisations.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="first_name",
            field=models.CharField(max_length=20, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="last_name",
            field=models.CharField(max_length=20, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisors",
                related_query_name="supervisors",
                to="competitions.submission",
                verbose_name="submission",
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="town",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="town"
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="zip",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter zip code in this format: '1234 AB'",
                        regex="^[1-9][0-9]{3} (?!SA|SD|SS)[A-Z]{2}",
                    )
                ],
                verbose_name="zip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission", unique_together={("competition", "title")},
        ),
    ]
