# Generated by Django 3.2.5 on 2021-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_auto_20210718_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="nomination_date",
            field=models.DateField(
                help_text="Communicated towards students in confirmation email as the latest date they will hear about their nomination",
                null=True,
                verbose_name="nomination date",
            ),
        ),
    ]
