# Generated by Django 3.2.5 on 2021-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0007_auto_20210725_2328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="competition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="competition date"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="nomination_date",
            field=models.DateField(
                blank=True,
                help_text="Communicated towards students in confirmation email as the latest date they will hear about their nomination",
                null=True,
                verbose_name="nomination date",
            ),
        ),
    ]
