# Generated by Django 3.2.5 on 2021-07-08 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("address_1", models.CharField(max_length=100)),
                ("address_2", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "zip",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter zip code in this format: '1234 AB'",
                                regex="^[1-9][0-9]{3} (?!SA|SD|SS)[A-Z]{2}",
                            )
                        ],
                    ),
                ),
                ("town", models.CharField(max_length=50)),
                ("courses_offered", models.ManyToManyField(to="organisations.Course")),
            ],
            options={
                "verbose_name": "school",
                "verbose_name_plural": "schools",
            },
        ),
        migrations.CreateModel(
            name="SchoolRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("remark", models.TextField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "remark",
                "verbose_name_plural": "remarks",
            },
        ),
    ]
