# Generated by Django 3.2.5 on 2021-07-18 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0004_auto_20210718_1147"),
        ("schools", "0002_auto_20210715_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="address_1",
            field=models.CharField(max_length=100, verbose_name="address 1"),
        ),
        migrations.AlterField(
            model_name="school",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="address 2"
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="courses_offered",
            field=models.ManyToManyField(
                related_name="schools",
                related_query_name="schools",
                to="organisations.Course",
                verbose_name="courses",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="school",
            name="town",
            field=models.CharField(max_length=50, verbose_name="town"),
        ),
        migrations.AlterField(
            model_name="school",
            name="zip",
            field=models.CharField(
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter zip code in this format: '1234 AB'",
                        regex="^[1-9][0-9]{3} (?!SA|SD|SS)[A-Z]{2}",
                    )
                ],
                verbose_name="zip",
            ),
        ),
        migrations.AlterField(
            model_name="schoolremark",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="schoolremark",
            name="remark",
            field=models.TextField(verbose_name="remark"),
        ),
        migrations.AlterField(
            model_name="schoolremark",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remarks",
                related_query_name="remarks",
                to="schools.school",
                verbose_name="school",
            ),
        ),
    ]
