# Generated by Django 3.2.5 on 2021-11-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0004_auto_20210718_1147"),
        ("schools", "0004_auto_20211126_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="courses_offered",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="schools",
                related_query_name="schools",
                to="organisations.Course",
                verbose_name="courses",
            ),
        ),
    ]
