# Generated by Django 4.0 on 2022-03-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_school_courses_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location_id',
            field=models.CharField(default=0, max_length=10, verbose_name='location id'),
            preserve_default=False,
        ),
    ]
