# Generated by Django 4.0 on 2022-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_school_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='in_service_region',
            field=models.BooleanField(default=False, help_text='Is this school considered to be located within our service region (normally, this is determined based on zip code)?', verbose_name='in service region'),
        ),
    ]
