# Generated by Django 4.0.5 on 2022-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_school_in_service_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='preferred_address',
            field=models.CharField(choices=[('1', 'location'), ('2', 'correspondence')], default='2', max_length=1, verbose_name='preferred address'),
        ),
    ]
