# Generated by Django 3.2.5 on 2021-11-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dayparts',
            field=models.ManyToManyField(related_name='dayparts', related_query_name='dayparts', to='secondments.Daypart', verbose_name='dayparts'),
        ),
    ]
