# Generated by Django 3.2.5 on 2021-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondments", "0002_alter_employee_dayparts"),
    ]

    operations = [
        migrations.AddField(
            model_name="daypart",
            name="short_name",
            field=models.SlugField(
                blank=True, max_length=8, null=True, verbose_name="short name"
            ),
        ),
    ]
