# Generated by Django 3.2.5 on 2021-11-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secondments", "0003_daypart_short_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daypart",
            name="short_name",
        ),
    ]
