# Generated by Django 4.0 on 2022-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondments', '0004_remove_daypart_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='public_transport',
            field=models.CharField(blank=True, choices=[('week', 'Week subscription'), ('weekend', 'Weekend subscription')], max_length=10, null=True, verbose_name='public transport'),
        ),
        migrations.AddField(
            model_name='employee',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='remarks'),
        ),
    ]
