# Generated by Django 4.0 on 2022-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondments', '0005_employee_public_transport_employee_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', help_text='Make sure the name matches the name registered at, for example, CampusDetachering.', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
