# Generated by Django 3.2.5 on 2021-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0011_auto_20210806_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idp',
            name='url_params',
            field=models.JSONField(blank=True, default=dict, help_text='Application-specific URL path parameters.', max_length=200, unique=True, verbose_name='URL Parameters'),
        ),
    ]
