# Generated by Django 3.2.5 on 2021-07-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_auto_20210715_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="course",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                related_query_name="courses",
                to="organisations.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(max_length=3, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="alternative_email",
            field=models.EmailField(
                blank=True,
                help_text="Notifications for new questions for this course will be sent to this address. If empty, the default email will be used.",
                max_length=254,
                null=True,
                verbose_name="alternative email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="courses",
            field=models.ManyToManyField(
                to="organisations.Course", verbose_name="courses"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                related_query_name="users",
                to="organisations.organisation",
                verbose_name="organisation",
            ),
        ),
    ]
