# Generated by Django 3.2.5 on 2021-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0004_auto_20210718_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=40, unique=True, verbose_name="name"),
        ),
    ]
