# Generated by Django 4.0 on 2022-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gov_slug',
            field=models.SlugField(blank=True, max_length=4, null=True, unique=True, verbose_name='government slug'),
        ),
    ]
