# Generated by Django 3.2.5 on 2021-07-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0003_auto_20210715_1808'),
        ('schools', '0002_auto_20210715_1808'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignee',
            name='alternative_email',
        ),
        migrations.AlterField(
            model_name='courseassignee',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_courses', related_query_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_questions', related_query_name='assigned_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', related_query_name='questions', to='organisations.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', related_query_name='questions', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', related_query_name='students', to='questions.question'),
        ),
    ]
