# Generated by Django 3.2.5 on 2021-07-18 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0003_auto_20210718_1147"),
        ("organisations", "0004_auto_20210718_1147"),
        ("questions", "0002_auto_20210715_1808"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="school_text",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="school (text)"
            ),
        ),
        migrations.AlterField(
            model_name="courseassignee",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_courses",
                related_query_name="assigned_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
        migrations.AlterField(
            model_name="courseassignee",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignee",
                related_query_name="assignee",
                to="organisations.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_questions",
                related_query_name="assigned_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="completed"),
        ),
        migrations.AlterField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                related_query_name="questions",
                to="organisations.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="question",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="question",
            name="research_question",
            field=models.TextField(
                blank=True, null=True, verbose_name="research question"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                related_query_name="questions",
                to="schools.school",
                verbose_name="school",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sub_questions",
            field=models.TextField(blank=True, null=True, verbose_name="sub questions"),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=20, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=20, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                related_query_name="students",
                to="questions.question",
                verbose_name="question",
            ),
        ),
    ]
