# Generated by Django 3.2.5 on 2021-08-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_auto_20210718_1147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "permissions": [
                    ("view_unassigned", "Can view questions not assigned to that user"),
                    ("complete_question", "Can change the completion status of tasks"),
                ],
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
    ]
