# Generated by Django 3.2.5 on 2021-08-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_question_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "permissions": [
                    ("view_unassigned", "Can view questions not assigned to that user"),
                    (
                        "complete_question",
                        "Can change the completion status of questions",
                    ),
                    ("change_assignee", "Can change the assignee of questions"),
                ],
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
    ]
