# Generated by Django 3.2.5 on 2021-11-26 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("questions", "0006_question_expected_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="Correspondence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date"
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence",
                        related_query_name="correspondence",
                        to="questions.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "correspondence",
                "verbose_name_plural": "correspondence",
            },
        ),
    ]
