# Generated by Django 3.2.5 on 2021-12-04 19:30

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("questions", "0007_auto_20211126_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
